### ISSUE TITLE
Falha no Github Actions para propor nova promessa cumprida a partir do website.

### ISSUE THREAD

**Issue by cfpgomes** [andrepcg/o-governo-ja-cumpriu#21]
No website, propus uma promessa cumprida, mas o Github Action responsável pela criação do Pull Request falhou.

Action: https://github.com/andrepcg/o-governo-ja-cumpriu/actions/runs/9286771090

**Comment by andrepcg** [comment]
Ha um bug quando se submete mais do que 1 link nesse formulario. Vou tentar corrigir, obrigado
